project_id = "tmoljmxeflnoodqagfuc"

[functions.admin-create-user]
verify_jwt = true

[functions.bulk-upload-people]
verify_jwt = true

[functions.design-interview]
verify_jwt = true

[functions.parse-document]
verify_jwt = true

[functions.refine-stage]
verify_jwt = true

[functions.settings]
verify_jwt = true

[functions.washup-summary]
verify_jwt = true
