project_id = "tmoljmxeflnoodqagfuc"

[functions.design-interview]
verify_jwt = true

[functions.parse-document]
verify_jwt = true

[functions.settings]
verify_jwt = true

[functions.washup-summary]
verify_jwt = true
